from django.urls import re_path

from api_test.api import ApiDoc, automationCase as Case, member, dynamic, user, VisitorRecord
from api_test.api import automationReport as Report
from api_test.api.global_parameter import HostTotal, AddHost, UpdateHost, DelHost, DisableHost, EnableHost
from api_test.api.projectList import ProjectList, AddProject, DelProject, \
    EnableProject, UpdateProject, DisableProject
from api_test.api.projectTitle import ProjectInfo

urlpatterns = [
    re_path(r'project/project_list', ProjectList.as_view()),
    re_path(r'project/add_project', AddProject.as_view()),
    re_path(r'project/update_project', UpdateProject.as_view()),
    re_path(r'project/del_project', DelProject.as_view()),
    re_path(r'project/disable_project', DisableProject.as_view()),
    re_path(r'project/enable_project', EnableProject.as_view()),
    re_path(r'title/project_info', ProjectInfo.as_view()),
    re_path(r'global/host_total', HostTotal.as_view()),
    re_path(r'global/add_host', AddHost.as_view()),
    re_path(r'global/update_host', UpdateHost.as_view()),
    re_path(r'global/del_host', DelHost.as_view()),
    re_path(r'global/disable_host', DisableHost.as_view()),
    re_path(r'global/enable_host', EnableHost.as_view()),
    re_path(r'api/group', ApiDoc.Group.as_view()),
    re_path(r'api/add_group', ApiDoc.AddGroup.as_view()),
    re_path(r'api/update_name_group', ApiDoc.UpdateNameGroup.as_view()),
    re_path(r'api/del_group', ApiDoc.DelGroup.as_view()),
    re_path(r'api/api_list', ApiDoc.ApiList.as_view()),
    re_path(r'api/add_api', ApiDoc.AddApi.as_view()),
    re_path(r'api/updateMock', ApiDoc.UpdateApiMockStatus.as_view()),
    re_path(r'api/lead_swagger', ApiDoc.LeadSwagger.as_view()),
    re_path(r'api/update_api', ApiDoc.UpdateApi.as_view()),
    re_path(r'api/del_api', ApiDoc.DelApi.as_view()),
    re_path(r'api/update_group', ApiDoc.UpdateGroup.as_view()),
    re_path(r'api/api_info', ApiDoc.ApiInfoDetail.as_view()),
    re_path(r'api/add_history', ApiDoc.AddHistory.as_view()),
    re_path(r'api/history_list', ApiDoc.HistoryList.as_view()),
    re_path(r'api/del_history', ApiDoc.DelHistory.as_view()),
    re_path(r'api/operation_history', ApiDoc.OperationHistory.as_view()),
    re_path(r'api/Download', ApiDoc.DownLoad.as_view()),
    re_path(r'api/download_doc', ApiDoc.download_doc),
    re_path(r'automation/group', Case.Group.as_view()),
    re_path(r'automation/add_group', Case.AddGroup.as_view()),
    re_path(r'automation/del_group', Case.DelGroup.as_view()),
    re_path(r'automation/update_name_group', Case.UpdateNameGroup.as_view()),
    re_path(r'automation/update_case_group', Case.UpdateGroup.as_view()),
    re_path(r'automation/case_list', Case.CaseList.as_view()),
    re_path(r'automation/add_case', Case.AddCase.as_view()),
    re_path(r'automation/update_case', Case.UpdateCase.as_view()),
    re_path(r'automation/del_case', Case.DelCase.as_view()),
    re_path(r'automation/DownloadCase', Case.DownLoadCase.as_view()),
    re_path(r'automation/api_list', Case.ApiList.as_view()),
    re_path(r'automation/api_info', Case.CaseApiInfo.as_view()),
    re_path(r'automation/add_new_api', Case.AddNewApi.as_view()),
    re_path(r'automation/get_correlation_response', Case.GetCorrelationResponse.as_view()),
    re_path(r'automation/add_old_api', Case.AddOldApi.as_view()),
    re_path(r'automation/update_api', Case.UpdateApi.as_view()),
    re_path(r'automation/del_api', Case.DelApi.as_view()),
    re_path(r'automation/start_test', Case.StartTest.as_view()),
    re_path(r'automation/add_time_task', Case.AddTimeTask.as_view()),
    re_path(r'automation/get_time_task', Case.GetTask.as_view()),
    re_path(r'automation/del_task', Case.DelTask.as_view()),
    re_path(r'automation/look_result', Case.LookResult.as_view()),
    re_path(r'automation/test_report', Case.TestReport.as_view()),
    re_path(r'report/auto_test_report', Report.AutoTestReport.as_view()),
    re_path(r'report/test_time', Report.TestTime.as_view()),
    re_path(r'report/lately_ten', Report.AutoLatelyTenTime.as_view()),
    re_path(r'member/project_member', member.ProjectMemberList.as_view()),
    re_path(r'member/email_config', member.EmailConfig.as_view()),
    re_path(r'member/del_email', member.DelEmail.as_view()),
    re_path(r'member/get_email', member.GetEmail.as_view()),
    re_path(r'dynamic/dynamic', dynamic.Dynamic.as_view()),
    re_path(r'user/login', user.obtain_auth_token),
    re_path(r'user/VisitorRecord', VisitorRecord.Record.as_view()),
]
